name: test
on:
  push:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Semver

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Init dependencies
        run: npm init
          
      # Add npm install step
      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        # uses: softprops/action-gh-release@v2
        run: npx semantic-release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}  

      # # Run your custom composite action
      # - name: Run Composite Action
      #   uses: ./
      #   env:
      #     GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Run Semantic Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        # run: npx semantic-release
        # shell: bash
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
