name: Build Application
on:
     push:
         branches:
             - main
jobs:
     build:
         runs-on: ubuntu-latest

         steps:
             - name: Checkout repository
               uses: actions/checkout@v2
               with:
                 # Important add this configuration to get the complete commit and tag history
                 fetch-depth: 0

             - name: Set up Node.js
               uses: actions/setup-node@v2
               with:
                 node-version: 14

             - name: Install dependencies
               run: npm install

             - name: Run Auto Semantic Version
               id: sematic-version-action
               uses: pedroalejandropt/auto-semantic-version@v1
               with:
                 ## Set a custom flag for release versions
                 release: release
                 # Set a custom flag for a specific workspace
                 namespace: specific-app

             - name: Print Version
               run: |
                 echo "${{ steps.sematic-version-action.outputs.version }}"
